/* Standalone game site player (generated by ExePlayer "Export as website") */
(() => {
  const $ = s => document.querySelector(s);
  const APPDIR = '/home/username/.wine/dosdevices/c:/files';
  // Several exported games can live on one domain (e.g. yourname.github.io), so keys are per game
  let LAYOUT_KEY = 'exeplayer.standalone.layout';
  let game = null, controls = null;

  const toastEl = $('#toast'); let tt;
  const toast = (m, ms = 4000) => { toastEl.textContent = m; toastEl.classList.remove('hidden'); clearTimeout(tt); tt = setTimeout(() => toastEl.classList.add('hidden'), ms); };
  window.ExePlayerToast = toast;
  const status = m => { $('#status').textContent = m || ''; };

  function savedLayout() { try { return JSON.parse(localStorage.getItem(LAYOUT_KEY)); } catch { return null; } }

  function play() {
    if (!navigator.serviceWorker?.controller) { location.reload(); return; }
    const s = game.settings || {};
    const exeDir = game.exe.includes('/') ? game.exe.slice(0, game.exe.lastIndexOf('/')) : '';
    const q = new URLSearchParams();
    q.set('app', game.zip); q.set('appBase', '../games/'); q.set('auto', 'true'); if (game.base && game.base !== game.root) { q.set('root', game.base); q.set('overlay', game.root); } else q.set('root', game.root);
    if (s.desktop) q.set('desktop', 'true');
    else { q.set('p', game.exe.split('/').pop()); q.set('w', APPDIR + (exeDir ? '/' + exeDir : '')); }
    if (s.args) q.set('args', s.args);
    if (s.res) q.set('resolution', s.res);
    q.set('bpp', s.bpp || '32'); q.set('sound', s.sound === false ? 'false' : 'true');

    $('#splash').classList.add('hidden'); $('#player').classList.remove('hidden'); document.body.classList.add('playing');
    const frame = $('#engineFrame');
    frame.src = 'engine/' + game.entry + '?' + q.toString().replace(/\+/g, '%20');
    controls = new TouchControls({
      overlay: $('#overlay'), frame, layout: savedLayout() || game.controls, title: game.name, icon: 'icon-192.png',
      onSave: layout => { try { localStorage.setItem(LAYOUT_KEY, JSON.stringify(layout)); } catch {} },
      onExit: () => { if (confirm('Quit the game? Unsaved in‑game progress will be lost.')) stop(); },
    });
    const d = document.documentElement;
    try { (d.requestFullscreen || d.webkitRequestFullscreen)?.call(d)?.catch?.(() => {}); } catch {}
    try { screen.orientation?.lock?.('landscape').catch(() => {}); } catch {}
    keepAwake(true);
  }
  let wakeLock = null;
  async function keepAwake(on) {
    try {
      if (on && !wakeLock && navigator.wakeLock) { wakeLock = await navigator.wakeLock.request('screen'); wakeLock.addEventListener('release', () => { wakeLock = null; }); }
      if (!on && wakeLock) { await wakeLock.release(); wakeLock = null; }
    } catch {}
  }
  document.addEventListener('visibilitychange', () => { if (!document.hidden && controls) keepAwake(true); });
  function stop() {
    controls?.destroy(); controls = null; keepAwake(false);
    $('#engineFrame').src = 'about:blank';
    $('#player').classList.add('hidden'); $('#splash').classList.remove('hidden'); document.body.classList.remove('playing');
    if (document.fullscreenElement) document.exitFullscreen?.();
  }

  $('#overlay').addEventListener('touchend', () => { try { $('#engineFrame').contentWindow.__exeplayerResumeAudio?.(); } catch {} }, true);
  window.addEventListener('message', e => {
    if (e.origin !== location.origin || !e.data || !e.data.exeplayer) return;
    if (e.data.exeplayer === 'error') toast('Engine error: ' + e.data.message, 7000);
  });
  $('#playBtn').onclick = play;
  $('#resetBtn').onclick = () => { localStorage.removeItem(LAYOUT_KEY); toast('Touch controls reset to the default layout.'); };
  document.addEventListener('gesturestart', e => e.preventDefault());

  const standaloneMode = matchMedia('(display-mode: standalone), (display-mode: fullscreen)').matches || navigator.standalone;
  if (/iPhone|iPad|iPod/.test(navigator.userAgent) && !standaloneMode) $('#installHint').classList.remove('hidden');

  (async () => {
    $('#playBtn').disabled = true; status('Loading…');
    try {
      game = await (await fetch('game.json', { cache: 'no-store' })).json();
      document.title = game.name; $('#gameTitle').textContent = game.name;
      LAYOUT_KEY = 'exeplayer.layout.' + location.pathname + game.zip;
    } catch { status('This site is missing game.json.'); return; }
    if (!('serviceWorker' in navigator)) { status('This browser can\'t run the game. Use Safari on iOS 16.4 or newer.'); return; }
    try {
      await navigator.serviceWorker.register('sw.js');
      if (!navigator.serviceWorker.controller) {
        await navigator.serviceWorker.ready;
        if (!sessionStorage.getItem('reloaded')) { sessionStorage.setItem('reloaded', '1'); location.reload(); return; }
      }
    } catch (e) { status('Setup failed: ' + e.message + ' (the site must be served over https).'); return; }
    $('#playBtn').disabled = false; status('');
  })();
})();
